apiVersion: apps/v1
kind: Deployment
metadata:
  name: dating-app-deployment
  labels:
    app: dating-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dating-app
  template:
    metadata:
      labels:
        app: dating-app
    spec:
      containers:
      - name: dating-app
        image: yourdockerhubuser/dating-app:replaceImageTag
        ports:
        - containerPort: 8080
