apiVersion: v1
kind: Service
metadata:
  name: dating-app-service
spec:
  selector:
    app: dating-app
  ports:
    - protocol: TCP
      port: 80          # service port
      targetPort: 8080  # forwards to containerPort inside pod
      nodePort: 32000   # external NodePort (avoid Jenkins conflict)
  type: NodePort
