apiVersion: v1
kind: Service
metadata:
  name: dating-app-service
  labels:
    app: dating-app-service
spec:
  selector:
    app: dating-app
  ports:
    - protocol: TCP
      port: 80          # Service port inside cluster
      targetPort: 8080  # forwards to containerPort inside pod
      nodePort: 30080   # fixed external port
  type: NodePort
